Fix #459. PS . Improve error message.
- In case of a similar problem, improve the error messages
  for the Py -> C++ convertion of gf
- E.g. in the case of the issue, the message would now say  :

---------

TypeError: Error: no suitable C++ overload found in implementation of function gf_fnt.set_from_imfreq

 set_from_imfreq(gf_view<legendre,matrix_valued> gl, gf_view<imfreq,matrix_valued> gw) -> void
 failed with the error :
  Cpp2py converter: Python to C++ :
  ... Conversion of a gf from Python to C++ triqs::gfs::gf_view<triqs::gfs::legendre, triqs::gfs::matrix_valued>
  ... Cannot convert the singularity of gf from Python type : pytriqs.gf.singularities.TailGf to the C++ type triqs::gfs::nothing

....